"use client";
import { useActionState, useState } from "react";
import { enrollExistingStudentAction, registerStudentAction, type ActionResult } from "@/lib/cohorts/actions";
import { Alert, Button, Card, CardContent, Input, Select, Tabs } from "@/components/ui";

export type StudentOption = { id: string; name: string; email: string };
export default function EnrollmentForms({ cohortId, students }: { cohortId: string; students: StudentOption[] }) {
  const [query, setQuery] = useState(""); const enroll = enrollExistingStudentAction.bind(null, cohortId); const [enrollState, submitEnrollment, enrolling] = useActionState<ActionResult | undefined, FormData>(enroll, undefined); const [newState, submitNew, creating] = useActionState<ActionResult | undefined, FormData>(registerStudentAction, undefined); const normalized = query.trim().toLocaleLowerCase("es"); const matches = students.filter((student) => !normalized || `${student.name} ${student.email}`.toLocaleLowerCase("es").includes(normalized));
  const existing = <Card><CardContent className="space-y-5 p-6"><div><h2 className="text-xl font-bold">Matricular estudiante registrado</h2><p className="mt-1 text-sm text-muted">Reutiliza su cuenta y evita identidades duplicadas.</p></div><form action={submitEnrollment} className="space-y-4"><Input label="Buscar por nombre o correo" value={query} onChange={(event) => setQuery(event.target.value)} /><Select name="userId" label="Estudiante" required defaultValue=""><option value="" disabled>Seleccionar estudiante</option>{matches.map((student) => <option key={student.id} value={student.id}>{student.name || "Sin nombre"} · {student.email}</option>)}</Select><Select name="entryType" label="Condición" defaultValue="repeater"><option value="repeater">Recursante</option><option value="new">Primera cursada</option></Select><Button type="submit" loading={enrolling} disabled={!matches.length}>Matricular estudiante</Button><Result state={enrollState} /></form></CardContent></Card>;
  const newStudent = <Card><CardContent className="space-y-5 p-6"><div><h2 className="text-xl font-bold">Registrar estudiante nuevo</h2><p className="mt-1 text-sm text-muted">Se crea una admisión. La cuenta se completa en el primer ingreso con Google.</p></div><form action={submitNew} className="space-y-4"><input type="hidden" name="cohortId" value={cohortId} /><input type="hidden" name="entryType" value="new" /><Input name="displayName" label="Nombre completo" required /><Input name="email" label="Correo de Google" type="email" required /><Button type="submit" loading={creating}>Registrar admisión</Button><Result state={newState} /></form></CardContent></Card>;
  return <Tabs label="Flujos de matriculación" items={[{ id: "existing", label: "Estudiante registrado", content: existing }, { id: "new", label: "Estudiante nuevo", content: newStudent }]} />;
}
function Result({ state }: { state?: ActionResult }) { return state ? <Alert variant={state.success ? "success" : "danger"}>{state.success ? state.message : state.error}</Alert> : null; }
