import EnrollmentRequestControls from "@/components/cohorts/EnrollmentRequestControls";
import { requireStaff } from "@/lib/cohorts/access";
import { normalizeDni, planEnrollmentRequestResolution } from "@/lib/cohorts/enrollment-requests";
import { createAdminServerClient } from "@/lib/pocketbase-server";
import type { EnrollmentRequest, User } from "@/types";
import { Alert, Badge, Card, CardContent, EmptyState, Input, LinkButton, PageHeader } from "@/components/ui";

export const dynamic = "force-dynamic";
type Query = { status?: string; request?: string; search?: string };
export default async function EnrollmentRequestsPage({ searchParams }: { searchParams: Promise<Query> }) {
  await requireStaff(); const query = await searchParams; const status = ["pending", "approved", "rejected"].includes(query.status || "") ? query.status! : "pending"; const pb = await createAdminServerClient(); const [requests, users] = await Promise.all([pb.collection("enrollment_requests").getFullList<EnrollmentRequest>({ filter: pb.filter("status = {:status}", { status }), expand: "cohort,reviewedBy,linkedUser,admission", sort: "-created" }), pb.collection("users").getFullList<User>({ sort: "name,email" })]);
  const search = query.search?.trim().toLocaleLowerCase("es") || ""; const visible = requests.filter((item) => !search || `${item.firstName} ${item.lastName} ${item.normalizedEmail} ${item.dni}`.toLocaleLowerCase("es").includes(search)); const selected = visible.find((item) => item.id === query.request) || visible[0]; const emailUser = selected ? users.find((user) => user.email?.trim().toLowerCase() === selected.normalizedEmail) : undefined; const dniUsers = selected ? users.filter((user) => user.dni && normalizeDni(user.dni) === selected.dni) : []; const plan = selected ? planEnrollmentRequestResolution({ emailUser, dniUsers }) : null;
  const href = (requestId: string) => `/staff/enrollment-requests?status=${status}${search ? `&search=${encodeURIComponent(search)}` : ""}&request=${requestId}`;
  return <div className="space-y-8"><PageHeader eyebrow="Revisión docente" title="Solicitudes de matriculación" description="Compará identidad y consecuencias antes de resolver cada solicitud." />
    <nav className="flex flex-wrap gap-2" aria-label="Estados de solicitud">{([['pending','Pendientes'],['approved','Aprobadas'],['rejected','Rechazadas']] as const).map(([value,label]) => <LinkButton key={value} href={`/staff/enrollment-requests?status=${value}`} variant={status === value ? "primary" : "secondary"} size="sm">{label}</LinkButton>)}</nav>
    <form className="max-w-xl"><input type="hidden" name="status" value={status} /><Input name="search" label="Buscar solicitud" type="search" defaultValue={query.search} placeholder="Nombre, correo o DNI" /></form>
    {!selected ? <EmptyState title="No hay solicitudes" description={`No encontramos solicitudes ${statusLabel(status)} con este criterio.`} /> : <div className="grid min-w-0 gap-6 lg:grid-cols-[minmax(18rem,0.7fr)_minmax(0,1.3fr)]"><aside className="space-y-2" aria-label="Listado de solicitudes">{visible.map((request) => <LinkButton key={request.id} href={href(request.id)} variant={request.id === selected.id ? "primary" : "secondary"} className="h-auto w-full justify-start p-4 text-left"><span><span className="block font-semibold">{request.lastName}, {request.firstName}</span><span className="mt-1 block text-xs font-normal">{request.normalizedEmail} · {request.expand?.cohort?.name}</span></span></LinkButton>)}</aside>
      <Card><CardContent className="p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted">Solicitada {formatDate(selected.created)}</p><h2 className="mt-1 text-2xl font-bold">{selected.firstName} {selected.lastName}</h2><p className="text-muted">{selected.expand?.cohort?.name}</p></div><Badge variant={statusVariant(selected.status)}>{statusLabel(selected.status)}</Badge></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Data label="DNI" value={selected.dni} /><Data label="Nacimiento" value={selected.birthDate} /><Data label="Correo de Google" value={selected.normalizedEmail} /><Data label="Teléfono" value={selected.phone} /></dl>
        {plan && <section className="mt-6 space-y-4"><Alert variant={plan.action === "conflict" ? "danger" : "info"} title="Coincidencia de identidad">{identityMessage(plan, emailUser, dniUsers)}</Alert><Card className="bg-surface-muted"><CardContent className="p-4"><h3 className="font-bold">Consecuencias de aprobar</h3><p className="mt-2 text-sm text-muted">{approvalConsequence(plan)}</p><h3 className="mt-4 font-bold">Consecuencias de rechazar</h3><p className="mt-2 text-sm text-muted">La solicitud quedará rechazada; no se creará ni modificará ninguna cuenta, admisión o matrícula.</p></CardContent></Card></section>}
        {selected.status === "pending" && plan?.action !== "conflict" ? <EnrollmentRequestControls requestId={selected.id} /> : selected.status === "pending" ? <Alert variant="danger" className="mt-5">El conflicto debe resolverse en los datos de identidad antes de aprobar o rechazar automáticamente.</Alert> : <div className="mt-5 text-sm text-muted"><p>{selected.resolution || "Solicitud resuelta."}</p>{selected.reviewedAt && <p>Revisada {formatDate(selected.reviewedAt)} por {selected.expand?.reviewedBy?.name || selected.expand?.reviewedBy?.email || "personal"}.</p>}</div>}
      </CardContent></Card></div>}
  </div>;
}
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function statusLabel(status: string) { return status === "pending" ? "Pendiente" : status === "approved" ? "Aprobada" : "Rechazada"; }
function statusVariant(status: string): "warning" | "success" | "danger" { return status === "pending" ? "warning" : status === "approved" ? "success" : "danger"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function identityMessage(plan: ReturnType<typeof planEnrollmentRequestResolution>, emailUser: User | undefined, dniUsers: User[]) { if (plan.action === "conflict") return `Conflicto: ${plan.reason}`; if (plan.action === "create_admission") return "No existe una cuenta coincidente."; const user = emailUser?.id === plan.userId ? emailUser : dniUsers.find((item) => item.id === plan.userId); return `Se reutilizará la cuenta de ${user?.name || user?.email || "este estudiante"}, coincidente por ${plan.matchedBy.replaceAll("_", " y ")}.`; }
function approvalConsequence(plan: ReturnType<typeof planEnrollmentRequestResolution>) { if (plan.action === "create_admission") return "Se creará una admisión pendiente para que el estudiante complete su cuenta con Google; la solicitud quedará aprobada."; if (plan.action === "use_user") return "La cuenta coincidente quedará matriculada en la cohorte solicitada y la solicitud quedará aprobada."; return "No puede aprobarse automáticamente mientras exista un conflicto de identidad."; }
