"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { Review, Sprint, User } from "@/types";
import { bookReviewSlot, cancelReviewBooking, createReviewSlotsBatch, deleteReviewSlot } from "@/lib/actions-reviews";
import { Alert, Badge, Button, Card, CardContent, Input, LinkButton, Select } from "@/components/ui";

type Filter = "all" | "available" | "reserved" | "completed" | "cancelled";
export default function ReviewsManager({ sprint, initialReviews, currentUser, cohortId }: { sprint: Sprint; initialReviews: Review[]; currentUser: User; cohortId?: string }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [filter, setFilter] = useState<Filter>("all"); const [creating, setCreating] = useState(false); const [feedback, setFeedback] = useState<{ ok: boolean; text: string } | null>(null);
  const [start, setStart] = useState(""); const [duration, setDuration] = useState(15); const [quantity, setQuantity] = useState(1); const [breakDuration, setBreakDuration] = useState(0); const [breakFrequency, setBreakFrequency] = useState(0);
  const staff = currentUser.role !== "estudiante"; const myBooking = !staff ? initialReviews.find(item => item.student === currentUser.id) : undefined;
  const ordered = useMemo(() => [...initialReviews].sort((a, b) => { const mine = Number(b.student === currentUser.id) - Number(a.student === currentUser.id); return mine || a.startTime.localeCompare(b.startTime); }), [initialReviews, currentUser.id]);
  const visible = ordered.filter(item => filter === "all" || reviewState(item) === filter); const groups = groupByDate(visible);
  const available = initialReviews.filter(item => reviewState(item) === "available").length; const reserved = initialReviews.filter(item => reviewState(item) === "reserved").length;
  const detailHref = (id: string) => cohortId ? `/cohorts/${cohortId}/reviews/appointments/${id}` : `/reviews/detail/${id}`;

  function run(action: () => Promise<{ success: boolean; error?: string }>, success: string) { setFeedback(null); startTransition(async () => { const result = await action(); if (!result.success) return setFeedback({ ok: false, text: result.error || "No pudimos completar la operación." }); setFeedback({ ok: true, text: success }); router.refresh(); }); }
  function create(event: React.FormEvent) { event.preventDefault(); if (!start) return; run(() => createReviewSlotsBatch(sprint.id, new Date(start).toISOString(), duration, quantity, breakDuration, breakFrequency), "Turnos creados correctamente."); setCreating(false); }

  return <section aria-label="Agenda de revisiones" className="space-y-6">
    {feedback && <Alert variant={feedback.ok ? "success" : "danger"}>{feedback.text}</Alert>}
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Turnos" value={initialReviews.length} /><Metric label="Disponibles" value={available} variant="success" /><Metric label="Reservados" value={reserved} variant="info" /></div>
    {myBooking && <Alert variant="info" title="Tu próxima revisión">{formatRange(myBooking)} <LinkButton href={detailHref(myBooking.id)} size="sm" className="ml-3">Ver mi turno</LinkButton></Alert>}
    <Card><CardContent className="p-5"><div className="flex flex-wrap items-end justify-between gap-4"><Select label="Filtrar agenda" value={filter} onChange={event => setFilter(event.target.value as Filter)} containerClassName="w-full sm:w-56"><option value="all">Todos</option><option value="available">Disponibles</option><option value="reserved">Reservados</option><option value="completed">Completados</option><option value="cancelled">Cancelados</option></Select>{staff && <Button onClick={() => setCreating(value => !value)}>{creating ? "Cerrar creación" : "Crear turnos"}</Button>}</div></CardContent></Card>
    {creating && staff && <Card><CardContent className="p-5 sm:p-6"><form onSubmit={create} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Input type="datetime-local" label="Inicio" value={start} onChange={event => setStart(event.target.value)} required /><Input type="number" min={5} label="Duración (minutos)" value={duration} onChange={event => setDuration(Number(event.target.value))} required /><Input type="number" min={1} max={30} label="Cantidad" value={quantity} onChange={event => setQuantity(Number(event.target.value))} required /><Input type="number" min={0} label="Pausa (minutos)" value={breakDuration} onChange={event => setBreakDuration(Number(event.target.value))} /><Input type="number" min={0} label="Pausa cada N turnos" value={breakFrequency} onChange={event => setBreakFrequency(Number(event.target.value))} /><div className="flex items-end"><Button type="submit" loading={pending} className="w-full">Crear agenda</Button></div></form></CardContent></Card>}
    <div className="space-y-8">{groups.map(group => <section key={group.date} aria-labelledby={`review-date-${group.key}`}><h2 id={`review-date-${group.key}`} className="mb-4 text-xl font-bold capitalize">{group.date}</h2><div className="grid gap-3">{group.items.map(review => { const state = reviewState(review); const mine = review.student === currentUser.id; return <Card key={review.id} className={mine ? "border-primary" : undefined}><CardContent className="grid gap-4 p-5 sm:grid-cols-[10rem_minmax(0,1fr)_auto] sm:items-center"><div><p className="text-lg font-bold tabular-nums">{formatTime(review.startTime)}</p><p className="text-xs text-muted">hasta {formatTime(review.endTime)}</p></div><div><Badge variant={stateVariant(state)}>{stateLabel(state)}</Badge><p className="mt-2 text-sm text-muted">{review.expand?.student?.name || (state === "available" ? "Sin reservar" : "Sin participante")}</p></div><div className="flex flex-wrap gap-2 sm:justify-end">{review.student && <LinkButton href={detailHref(review.id)} variant="secondary" size="sm">Abrir detalle</LinkButton>}{staff ? <>{review.student && <Button size="sm" variant="secondary" disabled={pending} onClick={() => run(() => cancelReviewBooking(review.id), "Turno liberado.")}>Liberar</Button>}<Button size="sm" variant="danger" disabled={pending} onClick={() => { if (window.confirm("¿Eliminar este turno?")) run(() => deleteReviewSlot(review.id), "Turno eliminado."); }}>Eliminar</Button></> : mine ? <Button size="sm" variant="secondary" disabled={pending} onClick={() => run(() => cancelReviewBooking(review.id), "Reserva cancelada.")}>Cancelar reserva</Button> : state === "available" && !myBooking ? <Button size="sm" disabled={pending} onClick={() => run(() => bookReviewSlot(review.id), "Turno reservado.")}>Reservar</Button> : null}</div></CardContent></Card>; })}</div></section>)}{!visible.length && <Alert variant="info" title="No hay turnos con este filtro">Elegí otro estado o creá nuevos turnos para la agenda.</Alert>}</div>
  </section>;
}

type State = "available" | "reserved" | "completed" | "cancelled";
function reviewState(review: Review): State { if (review.status === "completed") return "completed"; if (review.status === "cancelled") return "cancelled"; return review.student ? "reserved" : "available"; }
function stateLabel(state: State) { return { available: "Disponible", reserved: "Reservado", completed: "Completado", cancelled: "Cancelado" }[state]; }
function stateVariant(state: State): "success" | "info" | "neutral" | "danger" { return { available: "success", reserved: "info", completed: "neutral", cancelled: "danger" }[state] as "success" | "info" | "neutral" | "danger"; }
function Metric({ label, value, variant = "neutral" }: { label: string; value: number; variant?: "neutral" | "success" | "info" }) { return <Card><CardContent className="p-4"><Badge variant={variant}>{label}</Badge><p className="mt-3 text-3xl font-bold">{value}</p></CardContent></Card>; }
function groupByDate(reviews: Review[]) { const groups = new Map<string, Review[]>(); reviews.forEach(item => { const key = item.startTime.slice(0, 10); groups.set(key, [...(groups.get(key) || []), item]); }); return [...groups].map(([key, items]) => ({ key, date: new Intl.DateTimeFormat("es-AR", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${key}T12:00:00`)), items })); }
function formatTime(value: string) { return new Intl.DateTimeFormat("es-AR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function formatRange(review: Review) { return `${new Intl.DateTimeFormat("es-AR", { dateStyle: "long" }).format(new Date(review.startTime))}, ${formatTime(review.startTime)} a ${formatTime(review.endTime)}`; }
