import Link from "next/link";
import type { ReactNode } from "react";
import type { Cohort, Sprint, Week } from "@/types";
import type { TeacherStudentOverviewData } from "@/lib/teacher/data";
import { projectTeacherDeliveryStates, type TeacherDeliveryState } from "@/lib/teacher/delivery-state";
import { teacherAssignmentHref } from "@/lib/teacher/routes";
import { Alert, Badge, Card, CardContent, EmptyState, LinkButton, PageHeader } from "@/components/ui";

export default function TeacherStudentOverview({ cohort, data, returnHref, signal }: { cohort: Cohort; data: TeacherStudentOverviewData; returnHref: string; signal?: string }) {
  const projection = projectTeacherDeliveryStates({ students: [{ id: data.student.id }], assignments: data.assignments, deliveries: data.sources.deliveries.data, periods: data.periods, cohortId: cohort.id });
  const deliveriesAvailable = data.sources.deliveries.available;
  const attention = deliveriesAvailable ? projection.pairs.filter(pair => pair.state !== "submitted").length : 0;
  const status = data.enrollment.status === "active" ? "Matrícula activa" : "Matrícula finalizada";
  return <main className="mx-auto w-full max-w-[var(--content-dashboard)] space-y-8 px-4 py-8 lg:px-8">
    <PageHeader eyebrow={`${cohort.name} · Seguimiento docente`} title={personLabel(data.student)} description={`${status}. Evidencia académica limitada a esta cohorte.`} actions={<LinkButton href={returnHref} variant="secondary">Volver al tablero</LinkButton>} />
    {signal && <Alert variant="info" title="Contexto de seguimiento">Abriste esta ficha desde {signalLabel(signal)}. Las secciones conservan la evidencia completa de la cohorte.</Alert>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Períodos" value={data.periods.length} help="configurados" /><Metric label="Entregadas" value={deliveriesAvailable ? projection.counts.submitted : "—"} help={deliveriesAvailable ? `${projection.counts.total} aplicables` : "fuente no disponible"} variant={deliveriesAvailable ? "success" : "warning"} /><Metric label="Requieren atención" value={deliveriesAvailable ? attention : "—"} help={deliveriesAvailable ? `${projection.counts.overdue} vencidas` : "fuente no disponible"} variant={deliveriesAvailable && attention ? "warning" : deliveriesAvailable ? "neutral" : "warning"} /><Metric label="Consultas" value={data.sources.inquiries.available ? data.sources.inquiries.data.length : "—"} help={data.sources.inquiries.available ? "iniciadas por el estudiante" : "fuente no disponible"} variant={data.sources.inquiries.available ? "info" : "warning"} /></div>
    <section className="space-y-4" aria-labelledby="student-periods-heading"><div><h2 id="student-periods-heading" className="text-2xl font-bold">Progreso por período</h2><p className="mt-1 text-sm text-muted">Cada estado conduce al trabajo que lo originó.</p></div>{!deliveriesAvailable && <Alert variant="warning" title="Entregas no disponibles">No pudimos confirmar el progreso de los trabajos. Los estados no se infieren como pendientes.</Alert>}{!data.periods.length ? <EmptyState title="No hay períodos configurados" description="La cohorte todavía no tiene semanas o sprints para analizar." /> : <div className="grid gap-4 lg:grid-cols-2">{data.periods.map(period => <PeriodCard key={period.id} cohort={cohort} period={period} assignments={data.assignments} pairs={projection.pairs} studentId={data.student.id} deliveriesAvailable={deliveriesAvailable} />)}</div>}</section>
    <div className="grid gap-6 xl:grid-cols-2">
      <EvidenceSection title="Consultas" available={data.sources.inquiries.available}>{data.sources.inquiries.available && (data.sources.inquiries.data.length ? <div className="grid gap-3">{data.sources.inquiries.data.map(inquiry => <Link key={inquiry.id} href={`/cohorts/${cohort.id}/inquiries/${inquiry.id}`} className="rounded-md border p-4 hover:border-primary"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{inquiry.title}</strong><Badge variant={inquiry.status === "Pendiente" ? "warning" : "success"}>{inquiry.status}</Badge></div><p className="mt-2 text-sm text-muted">{inquiry.expand?.assignment?.title || inquiry.expand?.class?.title || inquiry.expand?.week?.title || "Consulta general"}</p></Link>)}</div> : <EmptyState title="Sin consultas registradas" description="El estudiante todavía no inició consultas en esta cohorte." />)}</EvidenceSection>
      <EvidenceSection title="Diagnóstico" available={data.sources.assessments.available}>{data.sources.assessments.available && (data.sources.assessments.data.length ? <div className="space-y-3"><p className="text-sm text-muted">{data.sources.assessments.data.length} intento{data.sources.assessments.data.length === 1 ? "" : "s"} registrado{data.sources.assessments.data.length === 1 ? "" : "s"}.</p><div className="flex flex-wrap items-center gap-3"><Badge variant="info">Último resultado</Badge><strong className="text-2xl">{data.sources.assessments.data[0].score}/{data.sources.assessments.data[0].totalQuestions}</strong><LinkButton href={`/cohorts/${cohort.id}/assessment-report?student=${data.student.id}`} size="sm" variant="secondary">Abrir diagnóstico</LinkButton></div></div> : <EmptyState title="Sin diagnóstico registrado" description="No hay resultados disponibles para este estudiante." />)}</EvidenceSection>
      <EvidenceSection title="Revisiones" available={data.sources.reviews.available}>{data.sources.reviews.available && (data.sources.reviews.data.length ? <div className="grid gap-3">{data.sources.reviews.data.map(review => <Link key={review.id} href={`/cohorts/${cohort.id}/reviews/appointments/${review.id}`} className="flex items-center justify-between gap-3 rounded-md border p-4 hover:border-primary"><span><strong>{review.expand?.sprint?.title || "Revisión"}</strong><span className="mt-1 block text-sm text-muted">{formatDateTime(review.startTime)}</span></span><Badge variant={review.status === "completed" ? "success" : review.status === "cancelled" ? "danger" : "info"}>{review.status === "completed" ? "Completada" : review.status === "cancelled" ? "Cancelada" : "Pendiente"}</Badge></Link>)}</div> : <EmptyState title="Sin revisiones registradas" description="No hay turnos asociados a este estudiante en la cohorte." />)}</EvidenceSection>
      <EvidenceSection title="Seguimiento solicitado" available={data.sources.followUps.available}>{data.sources.followUps.available && (data.sources.followUps.data.length ? <div className="space-y-3">{data.sources.followUps.data.map(survey => <Alert key={survey.id} variant="warning" title="Solicitó contacto docente">{survey.expand?.sprint?.title || "Sprint"} · {formatDateTime(survey.created)}</Alert>)}</div> : <EmptyState title="Sin solicitudes de contacto" description="No hay respuestas que pidan seguimiento docente." />)}</EvidenceSection>
    </div>
  </main>;
}

function PeriodCard({ cohort, period, assignments, pairs, studentId, deliveriesAvailable }: { cohort: Cohort; period: Week | Sprint; assignments: TeacherStudentOverviewData["assignments"]; pairs: ReturnType<typeof projectTeacherDeliveryStates>["pairs"]; studentId: string; deliveriesAvailable: boolean }) {
  const items = assignments.filter(assignment => (assignment.week || assignment.sprint) === period.id); const periodPairs = pairs.filter(pair => pair.periodId === period.id); const complete = items.length > 0 && periodPairs.every(pair => pair.state === "submitted");
  return <Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">{"number" in period ? `Semana ${period.number}` : "Sprint"}</p><h3 className="mt-1 text-lg font-bold">{period.title}</h3><p className="mt-1 text-xs text-muted">{period.endDate ? `Cierre ${formatDate(period.endDate)}` : "Sin fecha de cierre"}</p></div><Badge variant={!items.length ? "neutral" : !deliveriesAvailable ? "warning" : complete ? "success" : "warning"}>{!items.length ? "Sin actividades" : !deliveriesAvailable ? "No disponible" : complete ? "Completo" : "Pendiente"}</Badge></div>{items.length ? <ul className="mt-4 grid gap-2">{items.map(assignment => { const pair = periodPairs.find(value => value.assignmentId === assignment.id); return <li key={assignment.id}><Link href={teacherAssignmentHref(cohort.id, assignment.id, studentId)} className="flex min-h-11 items-center justify-between gap-3 rounded-md border px-3 py-2 hover:border-primary"><span className="font-medium">{assignment.title}</span>{deliveriesAvailable ? <DeliveryBadge state={pair?.state || "pending"} /> : <Badge variant="warning">No disponible</Badge>}</Link></li>; })}</ul> : <p className="mt-4 text-sm text-muted">No hay trabajos configurados para este período.</p>}</CardContent></Card>;
}
function EvidenceSection({ title, available, children }: { title: string; available: boolean; children: ReactNode }) { return <section aria-label={title}><Card className="h-full"><CardContent className="p-5"><h2 className="mb-4 text-xl font-bold">{title}</h2>{available ? children : <Alert variant="warning" title="Información no disponible">No pudimos cargar esta fuente. Reintentá actualizando la página.</Alert>}</CardContent></Card></section>; }
function DeliveryBadge({ state }: { state: TeacherDeliveryState }) { const value = state === "submitted" ? ["Entregada", "success"] as const : state === "overdue" ? ["Vencida", "danger"] as const : state === "due-soon" ? ["Vence pronto", "warning"] as const : ["Pendiente", "warning"] as const; return <Badge variant={value[1]}>{value[0]}</Badge>; }
function Metric({ label, value, help, variant = "neutral" }: { label: string; value: number | string; help: string; variant?: "neutral" | "success" | "warning" | "info" }) { return <Card><CardContent className="p-4"><Badge variant={variant}>{label}</Badge><p className="mt-3 text-3xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted">{help}</p></CardContent></Card>; }
function personLabel(person: TeacherStudentOverviewData["student"]) { return person.name || [person.firstName, person.lastName].filter(Boolean).join(" ") || person.email || "Estudiante"; }
function signalLabel(signal: string) { return signal.startsWith("period:") ? "un período del tablero" : signal.startsWith("assignment:") ? "un trabajo práctico" : signal === "follow-up" ? "una solicitud de contacto" : "una señal docente"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
