import Link from "next/link";
import type { User } from "@/types";
import type { TeacherAttentionData, TeacherAttentionSourceId } from "@/lib/teacher/data";
import type { TeacherAttentionItem, TeacherAttentionUrgency } from "@/lib/teacher/attention";
import { Alert, Badge, Card, CardContent, EmptyState, LinkButton, PageHeader } from "@/components/ui";

const sourceLabels: Record<TeacherAttentionSourceId, string> = { inquiries: "Consultas", deliveries: "Entregas", followUps: "Seguimientos", reviews: "Revisiones", enrollmentRequests: "Solicitudes" };

export default function TeacherAttentionWorkspace({ user, data, retryHref = "/" }: { user: User; data: TeacherAttentionData; retryHref?: string }) {
  const unavailable = (Object.entries(data.sources) as Array<[TeacherAttentionSourceId, TeacherAttentionData["sources"][TeacherAttentionSourceId]]>).filter(([, source]) => !source.available);
  const groups = (["critical", "upcoming", "routine"] as const).map(urgency => ({ urgency, items: data.items.filter(item => item.urgency === urgency) })).filter(group => group.items.length);
  return <main className="mx-auto w-full max-w-[var(--content-dashboard)] space-y-8 px-4 py-8 lg:px-8">
    <PageHeader eyebrow="Panel docente global" title={`Hola, ${firstName(user)}`} description="Atención pendiente de todas tus cohortes, ordenada por urgencia y conectada con su evidencia." actions={<LinkButton href="/cohorts" variant="secondary">Ver cohortes</LinkButton>} />
    <section aria-label="Resumen por fuente" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{(Object.entries(data.sources) as Array<[TeacherAttentionSourceId, TeacherAttentionData["sources"][TeacherAttentionSourceId]]>).map(([id, source]) => <Card key={id}><CardContent className="p-4"><Badge variant={source.available ? source.count ? "warning" : "neutral" : "danger"}>{sourceLabels[id]}</Badge><p className="mt-3 text-3xl font-bold tabular-nums">{source.available ? source.count : "—"}</p><p className="mt-1 text-xs text-muted">{source.available ? source.count ? "requieren atención" : "sin pendientes" : "fuente no disponible"}</p></CardContent></Card>)}</section>
    {unavailable.length > 0 && <Alert variant="warning" title="Información parcial">No pudimos cargar {unavailable.map(([id]) => sourceLabels[id].toLocaleLowerCase("es")).join(", ")}. Los demás resultados siguen disponibles y ninguna fuente fallida se cuenta como cero. <Link href={retryHref} className="ml-1 font-semibold underline">Reintentar</Link></Alert>}
    {data.allClear ? <EmptyState title="No hay trabajo pendiente" description="Todas las fuentes se cargaron correctamente y no encontramos señales que requieran atención." action={<LinkButton href="/cohorts" variant="secondary">Revisar cohortes</LinkButton>} /> : groups.length ? <section aria-labelledby="attention-queue-heading" className="space-y-7"><div><h2 id="attention-queue-heading" className="text-2xl font-bold">Atención docente</h2><p className="mt-1 text-sm text-muted">{data.items.length} caso{data.items.length === 1 ? "" : "s"} con una siguiente acción concreta.</p></div>{groups.map(group => <AttentionGroup key={group.urgency} {...group} />)}</section> : <EmptyState title="No hay casos visibles" description="Las fuentes disponibles no devolvieron pendientes, pero falta información por cargar antes de confirmar que todo está al día." action={<LinkButton href={retryHref}>Reintentar</LinkButton>} />}
  </main>;
}

function AttentionGroup({ urgency, items }: { urgency: TeacherAttentionUrgency; items: TeacherAttentionItem[] }) { const config = urgency === "critical" ? ["Atención inmediata", "danger"] as const : urgency === "upcoming" ? ["Próximos compromisos", "warning"] as const : ["Pendientes", "neutral"] as const; return <section aria-label={config[0]}><div className="mb-3 flex items-center gap-2"><Badge variant={config[1]}>{config[0]}</Badge><span className="text-sm text-muted">{items.length}</span></div><div className="grid gap-3">{items.map(item => <Card key={item.id}><CardContent className="grid gap-4 p-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="primary">{typeLabel(item.type)}</Badge><span className="text-xs font-semibold text-muted">{item.cohortName}</span></div><h3 className="mt-3 text-lg font-bold">{item.title}</h3><p className="mt-1 text-sm text-muted">{item.reason} · {item.contextLabel}</p><p className="mt-2 text-xs text-muted">{timeLabel(item)}</p></div><LinkButton href={item.href} className="w-full md:w-auto">{item.actionLabel}</LinkButton></CardContent></Card>)}</div></section>; }
function typeLabel(type: TeacherAttentionItem["type"]) { return { inquiry: "Consulta", "delivery-risk": "Entrega", "follow-up": "Seguimiento", review: "Revisión", "enrollment-request": "Solicitud" }[type]; }
function timeLabel(item: TeacherAttentionItem) { if (item.type === "review") return `Programada ${formatDateTime(item.timestamp)}`; if (item.type === "delivery-risk") return `Vencimiento ${formatDate(item.timestamp)}`; const hours = Math.max(0, Math.floor((Date.now() - new Date(item.timestamp).getTime()) / 3_600_000)); return hours < 24 ? `En espera hace ${hours} h` : `En espera hace ${Math.floor(hours / 24)} d`; }
function firstName(user: User) { return user.firstName || user.name?.trim().split(/\s+/)[0] || ""; }
function formatDate(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

