import type { Cohort, CohortEnrollment, StudentAdmission } from "@/types";
import { createAdminServerClient } from "@/lib/pocketbase-server";
import { requireAdmin } from "@/lib/cohorts/access";
import { updateCohortAction } from "@/lib/cohorts/actions";
import CohortForm from "@/components/cohorts/CohortForm";
import { AdmissionControls, EnrollmentControls } from "@/components/cohorts/AdminRecordControls";
import { Alert, Badge, Card, CardContent, LinkButton, PageHeader } from "@/components/ui";
import { MetricCard } from "@/components/analytics/MetricCard";

export const dynamic = "force-dynamic";
type Section = "summary" | "configuration" | "enrollments" | "admissions" | "content" | "analytics";
export default async function AdminCohortPage({ params, searchParams }: { params: Promise<{ cohortId: string }>; searchParams: Promise<{ section?: string; edit?: string }> }) {
  await requireAdmin(); const [{ cohortId }, query] = await Promise.all([params, searchParams]); const pb = await createAdminServerClient();
  const [cohort, enrollments, admissions] = await Promise.all([pb.collection("cohorts").getOne<Cohort>(cohortId), pb.collection("cohort_enrollments").getFullList<CohortEnrollment>({ filter: pb.filter("cohort = {:cohort}", { cohort: cohortId }), expand: "user", sort: "-status,-enrolledAt" }), pb.collection("student_admissions").getFullList<StudentAdmission>({ filter: pb.filter("cohort = {:cohort}", { cohort: cohortId }), sort: "status,displayName" })]);
  const section = (["configuration", "enrollments", "admissions", "content", "analytics"].includes(query.section || "") ? query.section : "summary") as Section; const active = enrollments.filter((item) => item.status === "active").length; const pendingAdmissions = admissions.filter((item) => item.status === "pending").length;
  const collectionName = cohort.mode === "weekly" ? "weeks" : "sprints"; const contentCount = await pb.collection(collectionName).getList(1, 1, { filter: pb.filter("cohort = {:cohort}", { cohort: cohortId }) }).then((result) => result.totalItems).catch(() => 0);
  return <div className="space-y-8"><PageHeader eyebrow="Administración de cohorte" title={cohort.name} description={`${cohort.mode === "weekly" ? "Modalidad semanal" : "Sprints y equipos"} · ${cohort.status === "active" ? "Activa" : "Archivada"}`} actions={<LinkButton href={`/admin/cohorts/${cohortId}/enrollments`}>Matricular estudiantes</LinkButton>} />
    <nav className="flex gap-2 overflow-x-auto border-b pb-2" aria-label="Secciones de cohorte">{([['summary','Resumen'],['configuration','Configuración'],['enrollments','Matrículas'],['admissions','Admisiones'],['content','Contenido'],['analytics','Analítica']] as const).map(([value,label]) => <LinkButton key={value} href={`/admin/cohorts/${cohortId}?section=${value}`} variant={section === value ? "primary" : "ghost"} size="sm">{label}</LinkButton>)}</nav>
    {section === "summary" && <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Matrículas activas" value={active} href={`/admin/cohorts/${cohortId}?section=enrollments`} /><MetricCard label="Matrículas históricas" value={enrollments.length - active} /><MetricCard label="Admisiones pendientes" value={pendingAdmissions} variant="warning" href={`/admin/cohorts/${cohortId}?section=admissions`} /><MetricCard label={cohort.mode === "weekly" ? "Semanas" : "Sprints"} value={contentCount} href={`/admin/cohorts/${cohortId}?section=content`} /></div><Card><CardContent className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><Data label="Identificador" value={cohort.slug} /><Data label="Estado" value={cohort.status === "active" ? "Activa" : "Archivada"} /><Data label="Inicio" value={formatDate(cohort.startDate)} /><Data label="Fin" value={formatDate(cohort.endDate)} /></CardContent></Card></div>}
    {section === "configuration" && <section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Configuración</h2>{query.edit === "1" ? <LinkButton href={`/admin/cohorts/${cohortId}?section=configuration`} variant="secondary">Cancelar</LinkButton> : <LinkButton href={`/admin/cohorts/${cohortId}?section=configuration&edit=1`}>Editar</LinkButton>}</div>{query.edit === "1" ? <CohortForm action={updateCohortAction.bind(null, cohortId)} cohort={cohort} /> : <Card><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><Data label="Nombre" value={cohort.name} /><Data label="Identificador" value={cohort.slug} /><Data label="Modalidad" value={cohort.mode === "weekly" ? "Semanal" : "Sprints y equipos"} /><Data label="Estado" value={cohort.status === "active" ? "Activa" : "Archivada"} /></CardContent></Card>}</section>}
    {section === "enrollments" && <RecordSection title={`Matrículas (${enrollments.length})`} empty="No hay matrículas registradas.">{enrollments.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.expand?.user?.name || item.expand?.user?.email}</p><p className="text-sm text-muted">{item.status === "active" ? "Activa" : "Finalizada"} · {item.entryType === "repeater" ? "Recursante" : "Primera cursada"}</p></div><EnrollmentControls id={item.id} status={item.status} /></CardContent></Card>)}</RecordSection>}
    {section === "admissions" && <RecordSection title={`Admisiones (${admissions.length})`} empty="No hay admisiones registradas.">{admissions.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.displayName}</p><p className="text-sm text-muted">{item.normalizedEmail} · {item.status}</p></div><AdmissionControls id={item.id} status={item.status} /></CardContent></Card>)}</RecordSection>}
    {section === "content" && <Card><CardContent className="p-6"><Badge variant="info">{contentCount} {cohort.mode === "weekly" ? "semanas" : "sprints"}</Badge><h2 className="mt-4 text-2xl font-bold">Contenido académico</h2><p className="mt-2 text-muted">Abrí la experiencia canónica para revisar publicación, clases y trabajos.</p><LinkButton href={`/cohorts/${cohortId}/${cohort.mode === "weekly" ? "weeks" : "sprints"}`} className="mt-5">Gestionar contenido</LinkButton></CardContent></Card>}
    {section === "analytics" && <Card><CardContent className="p-6"><h2 className="text-2xl font-bold">Analítica docente</h2><p className="mt-2 text-muted">Explorá progreso, entregas y consultas con contexto de cohorte.</p><LinkButton href={`/cohorts/${cohortId}/dashboard`} className="mt-5">Abrir tablero</LinkButton></CardContent></Card>}
  </div>;
}
function RecordSection({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) { const list = Array.isArray(children) ? children : [children]; return <section className="space-y-4"><h2 className="text-2xl font-bold">{title}</h2>{list.length ? <div className="grid gap-3">{children}</div> : <Alert variant="info">{empty}</Alert>}</section>; }
function Data({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("es-AR", { timeZone: "UTC" }).format(new Date(value)) : "Sin definir"; }
