"use client";

import { useState, useTransition } from "react";
import type { ContentBase, ContentBaseVersion } from "@/types";
import { applyContentBaseVersionAction, promoteContentBaseAction, restoreContentBaseVersionAction } from "@/lib/content/template-actions";
import { Alert, Badge, Button, Card, CardContent, Input, Select, Textarea } from "@/components/ui";

type VersionWithSummary = ContentBaseVersion & { summary: { kind: "course" | "week" | "section"; weeks: number; sections: number; blocks: number } };
const kindLabel = { course: "Curso", week: "Semana", section: "Sección" } as const;

export default function ContentBaseManager({ bases, selected }: { bases: ContentBase[]; selected?: { base: ContentBase; versions: VersionWithSummary[] } }) {
  const [message, setMessage] = useState<{ error?: string; success?: string }>({});
  const [pending, startTransition] = useTransition();
  const run = (operation: () => Promise<{ success: boolean; error?: string; message?: string }>) => startTransition(async () => { const result = await operation(); setMessage(result.success ? { success: result.message } : { error: result.error }); if (result.success) window.location.reload(); });
  return <div className="grid gap-7 xl:grid-cols-[minmax(18rem,0.7fr)_minmax(0,1.3fr)]"><div className="space-y-5"><NewBaseForm pending={pending} onSubmit={(value) => run(() => promoteContentBaseAction(value))} />
    <section><h2 className="mb-3 text-lg font-bold">Bases disponibles</h2><div className="grid gap-3">{bases.map((base) => <a key={base.id} href={`/admin/content-bases?base=${base.id}`}><Card className={selected?.base.id === base.id ? "border-primary" : "hover:border-primary"}><CardContent className="flex items-center justify-between gap-3 p-4"><div><strong>{base.name}</strong><p className="mt-1 text-xs text-muted">{kindLabel[base.kind]}</p></div><Badge variant={base.active ? "success" : "neutral"}>{base.active ? "Activa" : "Inactiva"}</Badge></CardContent></Card></a>)}</div></section></div>
    <div className="space-y-5">{message.error && <Alert variant="danger" title="No se pudo completar">{message.error}</Alert>}{message.success && <Alert variant="success" title="Operación completada">{message.success}</Alert>}
      {!selected ? <Alert title="Seleccioná una base">Consultá su historial, aplicá una versión o promové una copia nueva.</Alert> : <><section><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">{selected.base.name}</h2><Badge>{kindLabel[selected.base.kind]}</Badge></div><p className="mt-2 text-muted">{selected.base.description || "Sin descripción."}</p></section><PromoteVersionForm base={selected.base} pending={pending} onSubmit={(value) => run(() => promoteContentBaseAction(value))} /><section><h3 className="mb-3 text-lg font-bold">Historial inmutable</h3><div className="space-y-4">{selected.versions.map((version) => <Card key={version.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>Versión {version.versionNumber}</strong><p className="mt-1 text-xs text-muted">{new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(version.created))} · {version.sourceKind}</p></div>{selected.base.currentVersion === version.id && <Badge variant="primary">Actual</Badge>}</div><p className="mt-3 text-sm">{version.summary.weeks} semanas · {version.summary.sections} secciones · {version.summary.blocks} bloques</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><ApplyVersionForm version={version} kind={selected.base.kind} pending={pending} onApply={(target) => run(() => applyContentBaseVersionAction(version.id, target, true))} /><div className="rounded-md border p-3"><p className="text-sm font-semibold">Restaurar esta versión</p><p className="mt-1 text-xs text-muted">Crea una versión nueva; no elimina ni reescribe el historial.</p><Button className="mt-3" size="sm" variant="secondary" disabled={pending || selected.base.currentVersion === version.id} onClick={() => { if (confirm(`¿Restaurar la versión ${version.versionNumber} como una versión nueva?`)) run(() => restoreContentBaseVersionAction(selected.base.id, version.id, true)); }}>Restaurar</Button></div></div></CardContent></Card>)}</div></section></>}
    </div></div>;
}

function NewBaseForm({ pending, onSubmit }: { pending: boolean; onSubmit: (value: unknown) => void }) {
  const [kind, setKind] = useState<"course" | "week" | "section">("week"); const [name, setName] = useState(""); const [sourceId, setSourceId] = useState(""); const [description, setDescription] = useState("");
  return <Card><CardContent className="grid gap-3 p-4"><h2 className="text-lg font-bold">Crear una base</h2><Select label="Nivel" value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="course">Curso completo</option><option value="week">Semana</option><option value="section">Sección</option></Select><Input label="Nombre" value={name} onChange={(event) => setName(event.target.value)} /><Input label={`ID de ${kind === "course" ? "cohorte" : kind === "week" ? "semana" : "sección"} de origen`} value={sourceId} onChange={(event) => setSourceId(event.target.value)} /><Textarea label="Descripción" value={description} onChange={(event) => setDescription(event.target.value)} /><Button disabled={pending || !name || !sourceId} onClick={() => { if (confirm("¿Promover esta copia como nueva base?")) onSubmit({ name, description, kind, sourceId }); }}>Crear base versionada</Button></CardContent></Card>;
}

function PromoteVersionForm({ base, pending, onSubmit }: { base: ContentBase; pending: boolean; onSubmit: (value: unknown) => void }) {
  const [sourceId, setSourceId] = useState(""); const [note, setNote] = useState("");
  return <Card><CardContent className="grid gap-3 p-4"><h3 className="font-bold">Promover otra copia a esta base</h3><Input label={`ID de ${base.kind === "course" ? "cohorte" : base.kind === "week" ? "semana" : "sección"} de origen`} value={sourceId} onChange={(event) => setSourceId(event.target.value)} /><Input label="Nota de versión" value={note} onChange={(event) => setNote(event.target.value)} /><Button variant="secondary" disabled={pending || !sourceId} onClick={() => { if (confirm("La nueva versión sólo afectará copias futuras. ¿Continuar?")) onSubmit({ baseId: base.id, name: base.name, description: base.description ?? "", kind: base.kind, sourceId, note }); }}>Crear versión nueva</Button></CardContent></Card>;
}

function ApplyVersionForm({ version, kind, pending, onApply }: { version: VersionWithSummary; kind: ContentBase["kind"]; pending: boolean; onApply: (target: { cohortId: string; weekId?: string }) => void }) {
  const [cohortId, setCohortId] = useState(""); const [weekId, setWeekId] = useState("");
  return <div className="rounded-md border p-3"><p className="text-sm font-semibold">Copiar a un destino</p><p className="mt-1 text-xs text-muted">Se crearán {version.summary.weeks} semanas, {version.summary.sections} secciones y {version.summary.blocks} bloques en borrador.</p><div className="mt-3 grid gap-2"><Input label="ID de cohorte destino" value={cohortId} onChange={(event) => setCohortId(event.target.value)} />{kind === "section" && <Input label="ID de semana destino" value={weekId} onChange={(event) => setWeekId(event.target.value)} />}<Button size="sm" disabled={pending || !cohortId || (kind === "section" && !weekId)} onClick={() => { if (confirm("¿Crear esta copia independiente en borrador?")) onApply({ cohortId, ...(weekId ? { weekId } : {}) }); }}>Confirmar copia</Button></div></div>;
}
