import Link from "next/link";
import type { StudentContentSummary } from "@/lib/content/student";
import { studentWeekContentHref } from "@/lib/content/reader";
import { Badge, Card, CardContent, EmptyState, LinkButton } from "@/components/ui";

export default function StudentContentList({ cohortId, weekId, sections, progress, continueSection }: { cohortId: string; weekId: string; sections: StudentContentSummary[]; progress: { completed: number; total: number; percentage: number }; continueSection: StudentContentSummary | null }) {
  if (!sections.length) return <div><h2 id="academic-content-heading" className="mb-4 text-xl font-bold">Contenidos</h2><EmptyState title="Todavía no hay contenidos disponibles" description="Las secciones aparecerán aquí cuando el equipo docente las publique." /></div>;
  const href = (section: Pick<StudentContentSummary, "id" | "lastBlockKey" | "completed">) => studentWeekContentHref(cohortId, weekId, section);
  return <div className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="academic-content-heading" className="text-xl font-bold">Contenidos</h2><p className="mt-1 text-sm text-muted">{progress.completed} de {progress.total} secciones completadas</p><div className="mt-2 h-2 w-56 max-w-full overflow-hidden rounded-full bg-surface-muted" role="progressbar" aria-label="Progreso de contenidos de la semana" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percentage}><div className="h-full bg-primary" style={{ width: `${progress.percentage}%` }} /></div></div>{continueSection && <LinkButton href={href(continueSection)}>{continueSection.started ? "Continuar donde dejé" : "Comenzar recorrido"}</LinkButton>}</div>
    <ol className="grid gap-3">{sections.map((section, index) => <li key={section.id}><Link href={href(section)} className="group block"><Card className="transition-colors group-hover:border-primary"><CardContent className="flex items-start gap-4 p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-primary-soft font-bold text-primary">{index + 1}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="group-hover:text-primary">{section.title}</strong><Badge variant={section.completed ? "success" : section.started ? "info" : "neutral"}>{section.completed ? "Completada" : section.started ? "En curso" : "Pendiente"}</Badge></span>{section.summary && <span className="mt-1 line-clamp-2 text-sm leading-6 text-muted">{section.summary.replace(/<[^>]*>/g, " ")}</span>}</span><span aria-hidden="true" className="text-primary">→</span></CardContent></Card></Link></li>)}</ol>
  </div>;
}
