import Link from "next/link";
import type { ContentSection, ContentSectionProgress } from "@/types";
import type { PublicContentRevision } from "@/lib/content/projection";
import { Badge, LinkButton } from "@/components/ui";
import StudentContentRuntime from "./StudentContentRuntime";

export default function StudentContentReader({ cohortId, weekId, section, revision, progress, assetUrls, navigation, weekProgress }: { cohortId: string; weekId: string; section: ContentSection; revision: PublicContentRevision; progress: ContentSectionProgress | null; assetUrls: Record<string, string>; navigation: { previous: { id: string } | null; next: { id: string } | null; position: number; total: number }; weekProgress: { completed: number; total: number; percentage: number } }) {
  const href = (id: string) => `/cohorts/${cohortId}/weeks/${weekId}/content/${id}`;
  const completed = Boolean(progress?.completedAt && progress.requirementsRevision === revision.requirementsRevision);
  return <main className="mx-auto w-full max-w-[var(--content-reading)] px-4 pb-32 pt-8 lg:px-8"><LinkButton variant="ghost" href={`/cohorts/${cohortId}/weeks/${weekId}?section=content`}>← Volver a la semana</LinkButton><header className="mt-6"><div className="flex flex-wrap items-center gap-2"><Badge variant="primary">Sección {navigation.position} de {navigation.total}</Badge><Badge variant={completed ? "success" : "neutral"}>{completed ? "Completada" : progress ? "En curso" : "Pendiente"}</Badge></div><h1 className="mt-3 text-3xl font-bold tracking-tight">{section.title}</h1>{section.summary && <p className="mt-3 text-lg leading-8 text-muted">{section.summary.replace(/<[^>]*>/g, " ")}</p>}<div className="mt-5"><div className="flex justify-between text-xs text-muted"><span>Progreso semanal</span><span>{weekProgress.completed} de {weekProgress.total}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-surface-muted" role="progressbar" aria-label="Progreso de contenidos de la semana" aria-valuemin={0} aria-valuemax={100} aria-valuenow={weekProgress.percentage}><div className="h-full bg-primary" style={{ width: `${weekProgress.percentage}%` }} /></div></div></header><article className="mt-10 space-y-8"><StudentContentRuntime cohortId={cohortId} weekId={weekId} sectionId={section.id} revision={revision} assetUrls={assetUrls} /></article><nav aria-label="Navegación entre secciones" className="fixed inset-x-0 bottom-0 z-30 border-t bg-surface/95 px-4 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-3 shadow-[0_-6px_20px_rgba(0,0,0,0.08)] backdrop-blur lg:left-72"><div className="mx-auto flex max-w-[var(--content-reading)] items-center justify-between gap-3">{navigation.previous ? <Link className="min-h-11 rounded-md border px-4 py-2 font-semibold" href={href(navigation.previous.id)}>← Anterior</Link> : <span />}<span className="flex flex-col items-center text-sm tabular-nums text-muted"><span>{navigation.position}/{navigation.total}</span><Link href={`/cohorts/${cohortId}/weeks/${weekId}?section=content`} className="text-xs font-semibold underline underline-offset-2">Salir</Link></span>{navigation.next ? <Link className="min-h-11 rounded-md bg-primary px-4 py-2 font-semibold text-white dark:text-zinc-950" href={href(navigation.next.id)}>Siguiente →</Link> : <Link className="min-h-11 rounded-md border px-4 py-2 font-semibold" href={`/cohorts/${cohortId}/weeks/${weekId}?section=content`}>Finalizar</Link>}</div></nav></main>;
}
