import Link from "next/link";
import type { ContentActivityAttempt, ContentSection, User, Week } from "@/types";
import type { ContentAnalyticsFilters } from "@/lib/content/analytics-actions";
import type { aggregateTeachingContent } from "@/lib/content/teaching-analytics";
import { Badge, Button, Card, CardContent, EmptyState, Select } from "@/components/ui";

type Analytics = ReturnType<typeof aggregateTeachingContent>;
export default function TeachingContentDashboard({ cohortId, filters, weeks, allSections, allStudents, analytics, attempts }: { cohortId: string; filters: ContentAnalyticsFilters; weeks: Week[]; allSections: ContentSection[]; allStudents: User[]; analytics: Analytics; attempts: ContentActivityAttempt[] }) {
  const base = `/cohorts/${cohortId}/content-analytics`;
  const href = (patch: ContentAnalyticsFilters) => `${base}?${new URLSearchParams(Object.entries({ ...filters, ...patch }).filter(([, value]) => Boolean(value)) as string[][])}`;
  const studentById = new Map(allStudents.map((student) => [student.id, student]));
  const selectedStudent = filters.student ? analytics.students.find((student) => student.id === filters.student) : undefined;
  const selectedSection = filters.section ? analytics.sections.find((section) => section.id === filters.section) : undefined;
  return <div className="space-y-7"><form className="grid gap-3 rounded-lg border bg-surface p-4 sm:grid-cols-2 xl:grid-cols-5"><Select label="Semana" name="week" defaultValue={filters.week ?? ""}><option value="">Todas</option>{weeks.map((week) => <option key={week.id} value={week.id}>Semana {week.number}: {week.title}</option>)}</Select><Select label="Sección" name="section" defaultValue={filters.section ?? ""}><option value="">Todas</option>{allSections.filter((section) => !filters.week || section.week === filters.week).map((section) => <option key={section.id} value={section.id}>{section.title}</option>)}</Select><Select label="Alumno" name="student" defaultValue={filters.student ?? ""}><option value="">Todos</option>{allStudents.map((student) => <option key={student.id} value={student.id}>{student.name || student.email}</option>)}</Select><Select label="Actividad" name="activity" defaultValue={filters.activity ?? ""}><option value="">Todas</option>{[...new Map(analytics.sections.flatMap((section) => section.activities).map((activity) => [activity.activityKey, activity])).values()].map((activity) => <option key={activity.activityKey} value={activity.activityKey}>{activity.activityKey}</option>)}</Select><Button type="submit" className="self-end">Aplicar filtros</Button></form>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Resumen de trazabilidad"><Metric label="Estudiantes" value={analytics.totals.students} /><Metric label="Secciones" value={analytics.totals.sections} /><Metric label="Con aperturas registradas" value={analytics.totals.opened} /><Metric label="Finalizaciones vigentes" value={analytics.totals.completed} /><Metric label="Intentos" value={analytics.totals.attempts} /></section>
    {selectedStudent ? <StudentJourney student={selectedStudent} /> : selectedSection ? <SectionDetail section={selectedSection} students={analytics.students} href={href} /> : <Overview sections={analytics.sections} students={analytics.students} href={href} />}
    {(filters.activity || (selectedSection?.activities.length ?? 0) > 0) && <AttemptHistory attempts={attempts} studentById={studentById} sectionById={new Map(allSections.map((section) => [section.id, section]))} />}
  </div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <Card><CardContent className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{value}</p></CardContent></Card>; }

function Overview({ sections, students, href }: { sections: Analytics["sections"]; students: Analytics["students"]; href: (patch: ContentAnalyticsFilters) => string }) {
  if (!sections.length) return <EmptyState title="No hay secciones para analizar" description="Publicá o agregá contenidos para comenzar a registrar aperturas e intentos." />;
  return <div className="grid gap-7 xl:grid-cols-2"><section><h2 className="mb-3 text-xl font-bold">Por sección</h2><div className="grid gap-3">{sections.map((section) => <Link key={section.id} href={href({ section: section.id })}><Card className="hover:border-primary"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><strong>{section.title}</strong><Badge>{section.opened}/{section.enrolled} con apertura</Badge></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-sm"><Data label="Finalizaron" value={section.completed} /><Data label="Pendientes" value={section.pending} /><Data label="Actividades" value={section.activities.length} /></div></CardContent></Card></Link>)}</div></section><section><h2 className="mb-3 text-xl font-bold">Por alumno</h2><div className="grid gap-3">{students.map((student) => <Link key={student.id} href={href({ student: student.id })}><Card className="hover:border-primary"><CardContent className="flex items-center justify-between gap-4 p-4"><div><strong>{student.name}</strong><p className="mt-1 text-xs text-muted">{student.email}</p></div><div className="text-right text-sm"><p>{student.opened} con apertura</p><p className="text-muted">{student.completed} completadas · {student.attempts} intentos</p></div></CardContent></Card></Link>)}</div></section></div>;
}

function SectionDetail({ section, students, href }: { section: Analytics["sections"][number]; students: Analytics["students"]; href: (patch: ContentAnalyticsFilters) => string }) {
  return <div className="space-y-6"><section><h2 className="text-2xl font-bold">{section.title}</h2><p className="mt-1 text-sm text-muted">Aperturas registradas: {section.opened} de {section.enrolled}. Esta métrica no afirma lectura completa.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Finalizaciones" value={section.completed} /><Metric label="Pendientes" value={section.pending} /><Metric label="Actividades" value={section.activities.length} /></div></section><section><h3 className="mb-3 text-lg font-bold">Dominio por actividad</h3>{!section.activities.length ? <p className="text-sm text-muted">Esta sección no tiene actividades.</p> : <div className="grid gap-3 md:grid-cols-2">{section.activities.map((activity) => <Link key={activity.activityKey} href={href({ activity: activity.activityKey })}><Card className="hover:border-primary"><CardContent className="p-4"><strong>{activity.activityKey}</strong><p className="mt-2 text-sm text-muted">{activity.participants} participantes · {activity.attempts} intentos · {activity.mastered} con dominio</p></CardContent></Card></Link>)}</div>}</section><section><h3 className="mb-3 text-lg font-bold">Estado por alumno</h3><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="bg-surface-muted"><tr><th className="p-3">Alumno</th><th className="p-3">Apertura</th><th className="p-3">Última visualización</th><th className="p-3">Estado</th></tr></thead><tbody>{students.map((student) => { const item = student.sections.find((entry) => entry.id === section.id); return <tr key={student.id} className="border-t"><td className="p-3"><Link className="font-semibold text-primary" href={href({ student: student.id })}>{student.name}</Link></td><td className="p-3">{item?.opened ? `${item.viewCount} registrada${item.viewCount === 1 ? "" : "s"}` : "Sin apertura"}</td><td className="p-3">{formatDate(item?.lastViewedAt)}</td><td className="p-3"><Badge variant={item?.completed ? "success" : item?.opened ? "info" : "neutral"}>{item?.completed ? "Completada" : item?.opened ? "En curso" : "Pendiente"}</Badge></td></tr>; })}</tbody></table></div></section></div>;
}

function StudentJourney({ student }: { student: Analytics["students"][number] }) { return <section><h2 className="text-2xl font-bold">Recorrido de {student.name}</h2><p className="mt-1 text-sm text-muted">{student.email} · {student.attempts} intentos registrados</p><div className="mt-5 grid gap-3">{student.sections.map((section) => <Card key={section.id}><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{section.position}. {section.title}</strong><p className="mt-1 text-xs text-muted">Primera apertura: {formatDate(section.firstViewedAt)} · Última: {formatDate(section.lastViewedAt)}</p></div><Badge variant={section.completed ? "success" : section.opened ? "info" : "neutral"}>{section.completed ? "Completada" : section.opened ? "En curso" : "Pendiente"}</Badge></div>{section.activities.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{section.activities.map((activity) => <Badge key={activity.activityKey} variant={activity.mastered ? "success" : "neutral"}>{activity.activityKey}: {activity.mastered ? "dominada" : "pendiente"} ({activity.attempts})</Badge>)}</div>}</CardContent></Card>)}</div></section>; }

function AttemptHistory({ attempts, studentById, sectionById }: { attempts: ContentActivityAttempt[]; studentById: Map<string, User>; sectionById: Map<string, ContentSection> }) { return <section><h2 className="mb-3 text-xl font-bold">Historial de intentos</h2>{!attempts.length ? <EmptyState title="No hay intentos con estos filtros" description="El historial aparecerá cuando los alumnos respondan actividades." /> : <div className="space-y-3">{attempts.map((attempt) => <Card key={attempt.id}><CardContent className="p-4"><div className="flex flex-wrap items-center gap-2"><strong>{studentById.get(attempt.student)?.name || studentById.get(attempt.student)?.email || "Alumno"}</strong><Badge variant={attempt.outcome === "correct" || attempt.outcome === "satisfied" ? "success" : attempt.outcome === "incorrect" ? "danger" : "neutral"}>{attempt.outcome}</Badge></div><p className="mt-1 text-sm text-muted">{sectionById.get(attempt.section)?.title} · {attempt.activityKey} · {formatDate(attempt.attemptedAt)} · revisión {attempt.activityRevision}</p><pre className="mt-3 overflow-x-auto rounded-md bg-surface-muted p-3 text-xs">{JSON.stringify(attempt.response, null, 2)}</pre></CardContent></Card>)}</div>}</section>; }

function Data({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-surface-muted p-2"><strong className="block text-lg tabular-nums">{value}</strong><span className="text-xs text-muted">{label}</span></div>; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
